CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS history;
CREATE SCHEMA IF NOT EXISTS derived;

CREATE OR REPLACE FUNCTION core.catlas_are_string_tags(input jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    jsonb_typeof(input) = 'object'
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_each(input) AS tag_entry(key, value)
      WHERE jsonb_typeof(value) <> 'string'
    );
$$;

CREATE OR REPLACE FUNCTION core.catlas_has_no_reserved_tag_keys(input jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT NOT EXISTS (
    SELECT 1
    FROM jsonb_object_keys(input) AS key_name
    WHERE key_name = ANY (
      ARRAY[
        'feature_type',
        'relation_type',
        'geometry_kind',
        'is_closed',
        'version',
        'deleted_at',
        'changeset_id'
      ]
    )
  );
$$;

CREATE TABLE IF NOT EXISTS core.changesets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('open', 'published', 'abandoned')),
  comment text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);

CREATE TABLE IF NOT EXISTS core.nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  geom geometry(PointZ, 0) NOT NULL,
  feature_type text NOT NULL,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_by text,
  deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT nodes_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT nodes_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE IF NOT EXISTS core.ways (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_type text NOT NULL,
  geometry_kind text NOT NULL CHECK (geometry_kind IN ('line', 'area')),
  is_closed boolean NOT NULL DEFAULT false,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_by text,
  deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT ways_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT ways_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE IF NOT EXISTS core.way_nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  way_id bigint NOT NULL REFERENCES core.ways(id),
  node_id bigint NOT NULL REFERENCES core.nodes(id),
  seq integer NOT NULL,
  version integer NOT NULL DEFAULT 1,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT way_nodes_way_id_seq_key UNIQUE (way_id, seq)
);

CREATE TABLE IF NOT EXISTS core.relations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_type text NOT NULL,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_by text,
  deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT relations_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT relations_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE IF NOT EXISTS core.relation_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_id bigint NOT NULL REFERENCES core.relations(id),
  member_type text NOT NULL CHECK (member_type IN ('node', 'way', 'relation')),
  member_id bigint NOT NULL,
  seq integer NOT NULL,
  role text,
  version integer NOT NULL DEFAULT 1,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT relation_members_relation_id_seq_key UNIQUE (relation_id, seq)
);

CREATE TABLE IF NOT EXISTS derived.way_geometries (
  way_id bigint PRIMARY KEY REFERENCES core.ways(id),
  geom geometry(Geometry, 0) NOT NULL,
  bbox geometry(Polygon, 0) NOT NULL,
  source_version integer NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS derived.relation_geometries (
  relation_id bigint PRIMARY KEY REFERENCES core.relations(id),
  geom geometry(Geometry, 0) NOT NULL,
  bbox geometry(Polygon, 0) NOT NULL,
  source_version integer NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS history.node_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id bigint NOT NULL,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT node_versions_entity_version_key UNIQUE (node_id, version)
);

CREATE TABLE IF NOT EXISTS history.way_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  way_id bigint NOT NULL,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT way_versions_entity_version_key UNIQUE (way_id, version)
);

CREATE TABLE IF NOT EXISTS history.way_node_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  way_node_id bigint NOT NULL,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT way_node_versions_entity_version_key UNIQUE (way_node_id, version)
);

CREATE TABLE IF NOT EXISTS history.relation_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_id bigint NOT NULL,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT relation_versions_entity_version_key UNIQUE (relation_id, version)
);

CREATE TABLE IF NOT EXISTS history.relation_member_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_member_id bigint NOT NULL,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT relation_member_versions_entity_version_key UNIQUE (relation_member_id, version)
);

CREATE INDEX IF NOT EXISTS nodes_geom_gist_idx
  ON core.nodes
  USING gist (geom);

CREATE INDEX IF NOT EXISTS way_nodes_way_id_seq_idx
  ON core.way_nodes (way_id, seq);

CREATE INDEX IF NOT EXISTS way_nodes_node_id_idx
  ON core.way_nodes (node_id);

CREATE INDEX IF NOT EXISTS relation_members_relation_id_seq_idx
  ON core.relation_members (relation_id, seq);

CREATE INDEX IF NOT EXISTS way_geometries_geom_gist_idx
  ON derived.way_geometries
  USING gist (geom);

CREATE INDEX IF NOT EXISTS relation_geometries_geom_gist_idx
  ON derived.relation_geometries
  USING gist (geom);
